apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    mylabel: test1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
