apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: static-web1
spec:
  containers:
    - name: bash
      image: nginx:1.14.2
      command: ["/bin/bash", "-c", "--" ]
      args: ["while :; do echo '12345,abcde,miao,cipcip,1234567890'; sleep 3; done"]

---
apiVersion: v1
kind: Pod
metadata:
  name: static-web2
spec:
  containers:
    - name: bash
      image: nginx:1.14.2
      command: ["/bin/bash", "-c", "--" ]
      args: ["while :; do echo 'qwerty'; sleep 3; done"]
